name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Init nuget
      run: dotnet nuget add source https://nuget.pkg.github.com/conoscenza-no/index.json -n github -u conoscenza-no -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Pack
      run: dotnet pack --configuration Release --version-suffix beta
    - name: Publish package
      run: dotnet nuget push "bin/Release/Conoscenza.Ddd.0.1.0.nupkg" --source "github"
      
      
